# Generated by Django 5.2.10 on 2026-02-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
