# Generated by Django 5.1.5 on 2026-04-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_job_title_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Interview question asked by user')),
                ('answer', models.TextField(help_text='AI-generated answer to the question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Interview Question & Answer',
                'verbose_name_plural': 'Interview Questions & Answers',
                'ordering': ['-created_at'],
            },
        ),
    ]
