# Generated by Django 5.2.10 on 2026-01-28 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_prompt', models.TextField(default='You are an expert resume writer. Your task is to tailor the provided resume to match the given job description. \n\nGuidelines:\n- Highlight relevant skills and experiences that align with the job requirements\n- Use keywords from the job description naturally throughout the resume\n- Maintain the original structure and format\n- Keep the tone professional and achievement-oriented\n- Emphasize quantifiable accomplishments where possible\n- Do not add false information, only reframe and emphasize existing content\n\nPlease provide the tailored resume in a clear, professional format.', help_text='Custom prompt for AI resume tailoring')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
