# Generated by Django 5.2.10 on 2026-01-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_sample_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sample_resume',
        ),
    ]
