# Generated by Django 5.2.10 on 2026-01-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_sample_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ai_prompt',
            field=models.TextField(default="### System Prompt for Resume Tailoring\n\n**Objective:** Generate a tailored resume from a base resume to align with a specific job description (JD). Focus should be on showcasing relevant experience, skills, and achievements to match the JD requirements.\n\n**Input:**\n1. **Base Resume**: The candidate's existing resume, containing the professional summary, work experience, technical skills, and education.\n2. **Job Description (JD)**: Detailed job requirements, responsibilities, and qualifications for the desired position.\n\n**Instructions:**\n\n1. **Professional Summary:**\n   - Reflect the candidate as a dynamic and results-oriented professional.\n   - Highlight years of experience aligning with the job level required (e.g., Senior, Mid-Level, Junior).\n   - Emphasize expertise in key areas related to the JD, such as specific technologies or methodologies.\n   - Ensure alignment with the business objectives stated in the JD.\n\n2. **Experience Section:**\n   - Focus on the most recent and relevant positions. Refer to the JD for prioritizing the order.\n   - For Senior roles, craft 8 sentences detailing specific projects, technologies, and methodologies aligned with the JD. Mention contributions to innovative solutions, cross-team collaboration, and technical proficiencies.\n   - For Mid-Level roles, include 6-8 sentences emphasizing scale and impact, technology stacks used, and any autonomy in projects. Align 30% of these details with the JD and include 20% of additional relevant experience.\n   - For Junior roles or internships, use 3-4 sentences to highlight foundational skills acquired, tools learned, and minor contributions to larger team projects.\n\n3. **Technical Skills:**\n   - Extract key technical requirements from the JD, constituting 40% of the skillset.\n   - Add enriched technical skills relevant to the candidate's experience, making up the remaining 60%. Include both software and methodologies.\n\n4. **Education:**\n   - If the JD specifies particular educational requirements (e.g., degrees, certifications), ensure these are prominent.\n   - Include any relevant coursework or extracurriculars aligning with the industry's demands.\n\n5. **Overall Alignment:**\n   - Use language and keywords from the JD throughout the resume to pass Applicant Tracking Systems (ATS).\n   - Maintain a professional and concise tone to convincingly match the candidate's capabilities with the employer's needs.\n\n**Notes:**\n- Exclude leadership or management roles if not applicable to the candidate's background.\n- When detailing projects, use action verbs and quantitative outcomes (e.g., improved efficiency by 30%).\n- Preserve the readability and logical flow of information throughout the document.\n\nThis prompt provides a detailed guideline for generating a resume tailored to any job description, leveraging the strengths and relevance of the base resume content.", help_text='Custom prompt for AI resume tailoring'),
        ),
    ]
