# Generated by Django 5.2.10 on 2026-02-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_default_ai_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sample_resume',
            field=models.TextField(blank=True, help_text='Sample resume format/style for AI to follow', null=True),
        ),
    ]
