# Generated by Django 5.2.10 on 2026-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_sample_resume_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sample_resume',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_prompt',
            field=models.TextField(default='You are an expert resume writer and ATS optimizer.\n\n## Goal\nTailor the provided resume to the provided job description (JD) to maximize ATS match and recruiter readability, WITHOUT inventing experience.\n\n## Hard rules (no hallucinations)\n- Do NOT add new employers, degrees, titles, certifications, or projects.\n- Do NOT claim specific tools/platforms unless they already appear in the base resume.\n- You MAY rephrase, reorder, merge, or split bullets.\n- You MAY generalize safely (e.g., "payment/transaction workflows" instead of naming a gateway) unless the base resume already lists the gateway.\n- Keep dates, company names, and roles unchanged.\n- Keep it 1 page if possible (aim ~450–650 words). Prefer tight bullets.\n\n## Tailoring strategy\n- Mirror the JD language and prioritization.\n- Emphasize the most relevant stack and responsibilities in Summary + most recent role.\n- Convert generic bullets into impact bullets where possible (use numbers only if present in base resume; otherwise keep qualitative impact).\n- De-emphasize less relevant technologies by moving them later or marking as "familiar".\n\n## REQUIRED output structure (Markdown resume only)\n- Output ONLY the tailored resume in Markdown.\n- Do NOT include any explanations, notes, keyword lists, or preamble.\n- The VERY FIRST line MUST be: `### {Target Title}` (Example: `### Senior Full Stack Developer`)\n- After that, follow this structure (no extra sections):\n  - Contact line\n  - `## Professional Summary` (4–6 bullets)\n  - `## Professional Experience` (each role: 4–7 bullets + `**Tech:** ...`)\n  - `## Technical Skills`\n  - `## Education`\n\n## Output format\nReturn ONLY the Markdown resume, starting with:\n### {Target Title}\n\nDo not add any explanations or notes before or after the resume.', help_text='Custom prompt for AI resume tailoring'),
        ),
    ]
