# Generated by Django 5.2.10 on 2026-02-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_update_builtin_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_base_resume',
            field=models.TextField(blank=True, help_text='Default base resume content in Markdown format'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_name',
            field=models.CharField(blank=True, help_text='Default name to use for resume applications', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_prompt',
            field=models.TextField(default="@base resume.md This is my sample resume\n@jd.md is job description.\nupdate this resume which align with jd even tech stack.\nwe should change tech stack (you should change content (language, framework, cloud platform...) which related with main tech stack in base resume to things (language, framework, cloud platform...) which related with job description's tech stacks )\n\nOutput requirements:\n- Return ONLY the updated resume in Markdown.\n- Keep it professional and ATS-friendly.\n- Keep company names, titles, and dates as-is, but update wording/bullets to better match the JD.\n- When the base resume mentions technologies that don't match the JD, replace them with the closest JD-related alternatives and adjust the bullet content accordingly (language, frameworks, cloud platform, tooling).", help_text='Custom prompt for AI resume tailoring'),
        ),
    ]
